export const dealsData = [
    {
        deal: "Skiing and Snowboarding",
        price: "€170.56",
        category: "Experience",
        available: 60,
        expiration: "5 December 2024",
        status: "Active",
    },
    {
        deal: "Northern Lights Hunting",
        price: "€210.56",
        category: "Experience",
        available: 128,
        expiration: "5 December 2024",
        status: "Active",
    },
    {
        deal: "Villa Viima",
        price: "from €170.56",
        category: "Villa Collection",
        available: 10,
        expiration: "26 July 2024",
        status: "Archived",
    },
    {
        deal: "Husky Sledding",
        price: "€210.56",
        category: "Experience",
        available: 100,
        expiration: "26 July 2024",
        status: "Archived",
    },
    {
        deal: "Reindeer Safaris",
        price: "€210.56",
        category: "Experience",
        available: 30,
        expiration: "5 December 2024",
        status: "Processing",
    },
    {
        deal: "Villa Fort Aurora",
        price: "from €170.56",
        category: "Villa Collection",
        available: 12,
        expiration: "5 December 2025",
        status: "Drafts",
    },
    {
        deal: "Snowmobiling",
        price: "€170.56",
        category: "Experience",
        available: 14,
        expiration: "5 December 2024",
        status: "Active",
    },
    {
        deal: "Chalet U18",
        price: "from €170.56",
        category: "Villa Collection",
        available: 40,
        expiration: "26 July 2024",
        status: "Archived",
    },
];